version: '3.8'
services:
  redis-lh:
    container_name: redis-lh
    image: redis:6.2
    ports:
      - '6389:6379'
  db-lh:
    container_name: mysql-lh
    image: mysql:8.0.35
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - '127.0.0.1:7306:3306'
    volumes:
      - mysql_8:/var/lib/mysql
    command: mysqld


volumes:
  mysql_8:
